-- Create all tables with proper constraints
USE fra_documents;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  picture VARCHAR(512),
  provider VARCHAR(32) NOT NULL DEFAULT 'google',
  last_login DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_email (email)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS villages (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  gram_panchayat VARCHAR(255),
  block VARCHAR(255),
  district VARCHAR(255) NOT NULL,
  state VARCHAR(8) NOT NULL,
  population INT,
  st_population INT,
  total_households INT,
  pvtg_present BOOLEAN DEFAULT FALSE,
  tribal_groups JSON,
  total_claims INT DEFAULT 0,
  granted_claims INT DEFAULT 0,
  pending_claims INT DEFAULT 0,
  rejected_claims INT DEFAULT 0,
  ifr_granted_area FLOAT DEFAULT 0,
  cfr_granted_area FLOAT DEFAULT 0,
  cr_granted_area FLOAT DEFAULT 0,
  saturation_score INT DEFAULT 0,
  gps_lat FLOAT,
  gps_lng FLOAT,
  assets JSON,
  scheme_enrollments JSON,
  last_satellite_update VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_code (code),
  INDEX idx_state (state),
  INDEX idx_district (district)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS officers (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  officer_id VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  designation VARCHAR(64) NOT NULL,
  state VARCHAR(8),
  district VARCHAR(255),
  block VARCHAR(255),
  mobile VARCHAR(32) NOT NULL,
  email VARCHAR(255) NOT NULL,
  last_active DATETIME NOT NULL,
  total_claims_handled INT DEFAULT 0,
  pending_actions INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_officer_id (officer_id),
  INDEX idx_state (state),
  INDEX idx_district (district),
  INDEX idx_email (email)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS claims (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  claim_id VARCHAR(64) NOT NULL UNIQUE,
  claimant_name VARCHAR(255) NOT NULL,
  claimant_aadhaar VARCHAR(32),
  village_name VARCHAR(255) NOT NULL,
  village_code VARCHAR(64) NOT NULL,
  gram_panchayat VARCHAR(255),
  block VARCHAR(255),
  district VARCHAR(255) NOT NULL,
  state VARCHAR(8) NOT NULL,
  claim_type VARCHAR(8) NOT NULL,
  form_number VARCHAR(32),
  area_acres FLOAT NOT NULL,
  survey_khasra_no VARCHAR(64),
  claim_date DATE NOT NULL,
  verification_date DATE,
  decision_date DATE,
  status VARCHAR(32) NOT NULL,
  rejection_reason VARCHAR(1000),
  patte_number VARCHAR(128),
  patte_issued_date DATE,
  tribal_group VARCHAR(128),
  is_pvtg BOOLEAN DEFAULT FALSE,
  notes VARCHAR(512),
  gps_lat FLOAT,
  gps_lng FLOAT,
  boundary_geojson JSON,
  scanned_doc_url VARCHAR(512),
  ocr_data JSON,
  assigned_officer_id VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_claim_id (claim_id),
  INDEX idx_claim_state (state),
  INDEX idx_claim_district (district),
  INDEX idx_claim_village (village_code),
  INDEX idx_claim_status (status),
  INDEX idx_assigned_officer (assigned_officer_id),
  FOREIGN KEY fk_officer (assigned_officer_id) REFERENCES officers(officer_id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS grievances (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  grievance_id VARCHAR(64) NOT NULL UNIQUE,
  claimant_name VARCHAR(255) NOT NULL,
  claim_id VARCHAR(64),
  village_name VARCHAR(255) NOT NULL,
  block VARCHAR(255),
  district VARCHAR(255) NOT NULL,
  state VARCHAR(8) NOT NULL,
  category VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  priority VARCHAR(16) NOT NULL,
  assigned_officer_id VARCHAR(64),
  assigned_to VARCHAR(255),
  description VARCHAR(1000) NOT NULL,
  filed_date DATE,
  last_updated DATETIME,
  days_open INT DEFAULT 0,
  resolution VARCHAR(1000),
  source VARCHAR(64),
  channel VARCHAR(64),
  mobile VARCHAR(32),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_grievance_id (grievance_id),
  INDEX idx_state (state),
  INDEX idx_status (status),
  INDEX idx_priority (priority),
  INDEX idx_claim_id (claim_id),
  FOREIGN KEY fk_grievance_officer (assigned_officer_id) REFERENCES officers(officer_id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS data_blobs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `key` VARCHAR(128) NOT NULL UNIQUE,
  description VARCHAR(512),
  payload JSON NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_key (`key`)
) ENGINE=InnoDB;
