

"""init

Revision ID: 00a39d856a74
Revises: 
Create Date: 2026-02-23 00:24:38.737007

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00a39d856a74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_documents',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('raw_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('extracted_payload', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_documents_id'), 'master_documents', ['id'], unique=False)
    op.create_table('doc_claim_community_forest_resource',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('tehsil_taluka', sa.String(length=255), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('gram_panchayat', sa.String(length=255), nullable=True),
    sa.Column('gram_sabha', sa.String(length=255), nullable=True),
    sa.Column('gram_sabha_member_name', sa.String(length=255), nullable=True),
    sa.Column('category_scheduled_tribe', sa.String(length=255), nullable=True),
    sa.Column('category_other_traditional_forest_dweller', sa.String(length=255), nullable=True),
    sa.Column('khasra_compartment_number', sa.String(length=100), nullable=True),
    sa.Column('bordering_village', sa.String(length=255), nullable=True),
    sa.Column('boundary_description', sa.Text(), nullable=True),
    sa.Column('community_forest_resource_evidence_list', sa.Text(), nullable=True),
    sa.Column('evidence_item', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['master_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_dccfr_district', 'doc_claim_community_forest_resource', ['district'], unique=False)
    op.create_index('idx_dccfr_state', 'doc_claim_community_forest_resource', ['state'], unique=False)
    op.create_index('idx_dccfr_village', 'doc_claim_community_forest_resource', ['village'], unique=False)
    op.create_table('doc_claim_community_rights',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('tehsil_taluka', sa.String(length=255), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('gram_panchayat', sa.String(length=255), nullable=True),
    sa.Column('gram_sabha', sa.String(length=255), nullable=True),
    sa.Column('community_type_fdst', sa.String(length=255), nullable=True),
    sa.Column('community_type_otfd', sa.String(length=255), nullable=True),
    sa.Column('community_right_nistar', sa.Text(), nullable=True),
    sa.Column('right_minor_forest_produce', sa.Text(), nullable=True),
    sa.Column('community_right_resource_use', sa.Text(), nullable=True),
    sa.Column('community_right_grazing', sa.Text(), nullable=True),
    sa.Column('community_right_nomadic_pastoralist_access', sa.Text(), nullable=True),
    sa.Column('community_tenure_habitat', sa.Text(), nullable=True),
    sa.Column('community_right_biodiversity_ipr_tk', sa.Text(), nullable=True),
    sa.Column('other_traditional_right', sa.Text(), nullable=True),
    sa.Column('evidence_item', sa.Text(), nullable=True),
    sa.Column('other_information', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['master_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_dccr_district', 'doc_claim_community_rights', ['district'], unique=False)
    op.create_index('idx_dccr_state', 'doc_claim_community_rights', ['state'], unique=False)
    op.create_index('idx_dccr_village', 'doc_claim_community_rights', ['village'], unique=False)
    op.create_table('doc_claim_forest_land',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('claimant_name', sa.String(length=255), nullable=True),
    sa.Column('father_mother_name', sa.String(length=255), nullable=True),
    sa.Column('spouse_name', sa.String(length=255), nullable=True),
    sa.Column('address_full', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('tehsil_taluka', sa.String(length=255), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('gram_panchayat', sa.String(length=255), nullable=True),
    sa.Column('gram_sabha', sa.String(length=255), nullable=True),
    sa.Column('category_scheduled_tribe', sa.String(length=255), nullable=True),
    sa.Column('category_other_traditional_forest_dweller', sa.String(length=255), nullable=True),
    sa.Column('family_member_name', sa.String(length=255), nullable=True),
    sa.Column('family_member_age', sa.String(length=100), nullable=True),
    sa.Column('dependent_name', sa.String(length=255), nullable=True),
    sa.Column('land_extent_habitation', sa.String(length=100), nullable=True),
    sa.Column('land_extent_self_cultivation', sa.String(length=100), nullable=True),
    sa.Column('land_extent_forest_village', sa.String(length=100), nullable=True),
    sa.Column('disputed_land_description', sa.Text(), nullable=True),
    sa.Column('existing_pattas_leases_grants', sa.Text(), nullable=True),
    sa.Column('rehabilitation_land', sa.Text(), nullable=True),
    sa.Column('displaced_from_land', sa.Text(), nullable=True),
    sa.Column('other_traditional_right', sa.Text(), nullable=True),
    sa.Column('evidence_item', sa.Text(), nullable=True),
    sa.Column('other_information', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['master_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_dcf_land_district', 'doc_claim_forest_land', ['district'], unique=False)
    op.create_index('idx_dcf_land_state', 'doc_claim_forest_land', ['state'], unique=False)
    op.create_index('idx_dcf_land_village', 'doc_claim_forest_land', ['village'], unique=False)
    op.create_table('doc_title_community_forest_resources',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('tehsil_taluka', sa.String(length=255), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('gram_panchayat', sa.String(length=255), nullable=True),
    sa.Column('gram_sabha', sa.String(length=255), nullable=True),
    sa.Column('community_type_scheduled_tribe', sa.String(length=255), nullable=True),
    sa.Column('community_type_other_tfd', sa.String(length=255), nullable=True),
    sa.Column('community_type_both', sa.String(length=255), nullable=True),
    sa.Column('khasra_compartment_number', sa.String(length=100), nullable=True),
    sa.Column('boundary_description', sa.Text(), nullable=True),
    sa.Column('customary_boundary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['master_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_dtcfrs_district', 'doc_title_community_forest_resources', ['district'], unique=False)
    op.create_index('idx_dtcfrs_state', 'doc_title_community_forest_resources', ['state'], unique=False)
    op.create_index('idx_dtcfrs_village', 'doc_title_community_forest_resources', ['village'], unique=False)
    op.create_table('doc_title_community_forest_rights',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('community_right_holder_name', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('tehsil_taluka', sa.String(length=255), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('gram_panchayat', sa.String(length=255), nullable=True),
    sa.Column('gram_sabha', sa.String(length=255), nullable=True),
    sa.Column('category_scheduled_tribe', sa.String(length=255), nullable=True),
    sa.Column('category_other_traditional_forest_dweller', sa.String(length=255), nullable=True),
    sa.Column('community_right_nature', sa.Text(), nullable=True),
    sa.Column('title_conditions', sa.Text(), nullable=True),
    sa.Column('khasra_compartment_number', sa.String(length=100), nullable=True),
    sa.Column('boundary_description', sa.Text(), nullable=True),
    sa.Column('customary_boundary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['master_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_dtcfr_district', 'doc_title_community_forest_rights', ['district'], unique=False)
    op.create_index('idx_dtcfr_state', 'doc_title_community_forest_rights', ['state'], unique=False)
    op.create_index('idx_dtcfr_village', 'doc_title_community_forest_rights', ['village'], unique=False)
    op.create_table('doc_title_under_occupation',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title_holder_name', sa.String(length=255), nullable=True),
    sa.Column('father_mother_name', sa.String(length=255), nullable=True),
    sa.Column('spouse_name', sa.String(length=255), nullable=True),
    sa.Column('dependent_name', sa.String(length=255), nullable=True),
    sa.Column('title_address_full', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('tehsil_taluka', sa.String(length=255), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('gram_panchayat', sa.String(length=255), nullable=True),
    sa.Column('gram_sabha', sa.String(length=255), nullable=True),
    sa.Column('category_scheduled_tribe', sa.String(length=255), nullable=True),
    sa.Column('category_other_traditional_forest_dweller', sa.String(length=255), nullable=True),
    sa.Column('title_land_area_measure', sa.String(length=100), nullable=True),
    sa.Column('khasra_compartment_number', sa.String(length=100), nullable=True),
    sa.Column('boundary_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['master_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_dtuo_district', 'doc_title_under_occupation', ['district'], unique=False)
    op.create_index('idx_dtuo_state', 'doc_title_under_occupation', ['state'], unique=False)
    op.create_index('idx_dtuo_village', 'doc_title_under_occupation', ['village'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dtuo_village', table_name='doc_title_under_occupation')
    op.drop_index('idx_dtuo_state', table_name='doc_title_under_occupation')
    op.drop_index('idx_dtuo_district', table_name='doc_title_under_occupation')
    op.drop_table('doc_title_under_occupation')
    op.drop_index('idx_dtcfr_village', table_name='doc_title_community_forest_rights')
    op.drop_index('idx_dtcfr_state', table_name='doc_title_community_forest_rights')
    op.drop_index('idx_dtcfr_district', table_name='doc_title_community_forest_rights')
    op.drop_table('doc_title_community_forest_rights')
    op.drop_index('idx_dtcfrs_village', table_name='doc_title_community_forest_resources')
    op.drop_index('idx_dtcfrs_state', table_name='doc_title_community_forest_resources')
    op.drop_index('idx_dtcfrs_district', table_name='doc_title_community_forest_resources')
    op.drop_table('doc_title_community_forest_resources')
    op.drop_index('idx_dcf_land_village', table_name='doc_claim_forest_land')
    op.drop_index('idx_dcf_land_state', table_name='doc_claim_forest_land')
    op.drop_index('idx_dcf_land_district', table_name='doc_claim_forest_land')
    op.drop_table('doc_claim_forest_land')
    op.drop_index('idx_dccr_village', table_name='doc_claim_community_rights')
    op.drop_index('idx_dccr_state', table_name='doc_claim_community_rights')
    op.drop_index('idx_dccr_district', table_name='doc_claim_community_rights')
    op.drop_table('doc_claim_community_rights')
    op.drop_index('idx_dccfr_village', table_name='doc_claim_community_forest_resource')
    op.drop_index('idx_dccfr_state', table_name='doc_claim_community_forest_resource')
    op.drop_index('idx_dccfr_district', table_name='doc_claim_community_forest_resource')
    op.drop_table('doc_claim_community_forest_resource')
    op.drop_index(op.f('ix_master_documents_id'), table_name='master_documents')
    op.drop_table('master_documents')
    # ### end Alembic commands ###
