CREATE TABLE master_documents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  file_path TEXT NOT NULL,
  document_type VARCHAR(100) NULL,
  language VARCHAR(20) NULL,
  upload_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  processing_status VARCHAR(50) DEFAULT 'PENDING',
  raw_text LONGTEXT NULL,
  extracted_payload LONGTEXT NULL,
  KEY idx_master_documents_id (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE doc_claim_forest_land (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  document_id BIGINT UNSIGNED UNIQUE,
  claimant_name VARCHAR(255) NULL,
  father_mother_name VARCHAR(255) NULL,
  spouse_name VARCHAR(255) NULL,
  address_full TEXT NULL,
  state VARCHAR(255) NULL,
  district VARCHAR(255) NULL,
  tehsil_taluka VARCHAR(255) NULL,
  village VARCHAR(255) NULL,
  gram_panchayat VARCHAR(255) NULL,
  gram_sabha VARCHAR(255) NULL,
  category_scheduled_tribe VARCHAR(255) NULL,
  category_other_traditional_forest_dweller VARCHAR(255) NULL,
  family_member_name VARCHAR(255) NULL,
  family_member_age VARCHAR(100) NULL,
  dependent_name VARCHAR(255) NULL,
  land_extent_habitation VARCHAR(100) NULL,
  land_extent_self_cultivation VARCHAR(100) NULL,
  land_extent_forest_village VARCHAR(100) NULL,
  disputed_land_description TEXT NULL,
  existing_pattas_leases_grants TEXT NULL,
  rehabilitation_land TEXT NULL,
  displaced_from_land TEXT NULL,
  other_traditional_right TEXT NULL,
  evidence_item TEXT NULL,
  other_information TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dcf_land_document FOREIGN KEY (document_id) REFERENCES master_documents (id) ON DELETE CASCADE,
  INDEX idx_dcf_land_state (state),
  INDEX idx_dcf_land_district (district),
  INDEX idx_dcf_land_village (village)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE doc_claim_community_rights (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  document_id BIGINT UNSIGNED UNIQUE,
  state VARCHAR(255) NULL,
  district VARCHAR(255) NULL,
  tehsil_taluka VARCHAR(255) NULL,
  village VARCHAR(255) NULL,
  gram_panchayat VARCHAR(255) NULL,
  gram_sabha VARCHAR(255) NULL,
  community_type_fdst VARCHAR(255) NULL,
  community_type_otfd VARCHAR(255) NULL,
  community_right_nistar TEXT NULL,
  right_minor_forest_produce TEXT NULL,
  community_right_resource_use TEXT NULL,
  community_right_grazing TEXT NULL,
  community_right_nomadic_pastoralist_access TEXT NULL,
  community_tenure_habitat TEXT NULL,
  community_right_biodiversity_ipr_tk TEXT NULL,
  other_traditional_right TEXT NULL,
  evidence_item TEXT NULL,
  other_information TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dccr_document FOREIGN KEY (document_id) REFERENCES master_documents (id) ON DELETE CASCADE,
  INDEX idx_dccr_state (state),
  INDEX idx_dccr_district (district),
  INDEX idx_dccr_village (village)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE doc_claim_community_forest_resource (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  document_id BIGINT UNSIGNED UNIQUE,
  state VARCHAR(255) NULL,
  district VARCHAR(255) NULL,
  tehsil_taluka VARCHAR(255) NULL,
  village VARCHAR(255) NULL,
  gram_panchayat VARCHAR(255) NULL,
  gram_sabha VARCHAR(255) NULL,
  gram_sabha_member_name VARCHAR(255) NULL,
  category_scheduled_tribe VARCHAR(255) NULL,
  category_other_traditional_forest_dweller VARCHAR(255) NULL,
  khasra_compartment_number VARCHAR(100) NULL,
  bordering_village VARCHAR(255) NULL,
  boundary_description TEXT NULL,
  community_forest_resource_evidence_list TEXT NULL,
  evidence_item TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dccfr_document FOREIGN KEY (document_id) REFERENCES master_documents (id) ON DELETE CASCADE,
  INDEX idx_dccfr_state (state),
  INDEX idx_dccfr_district (district),
  INDEX idx_dccfr_village (village)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE doc_title_under_occupation (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  document_id BIGINT UNSIGNED UNIQUE,
  title_holder_name VARCHAR(255) NULL,
  father_mother_name VARCHAR(255) NULL,
  spouse_name VARCHAR(255) NULL,
  dependent_name VARCHAR(255) NULL,
  title_address_full TEXT NULL,
  state VARCHAR(255) NULL,
  district VARCHAR(255) NULL,
  tehsil_taluka VARCHAR(255) NULL,
  village VARCHAR(255) NULL,
  gram_panchayat VARCHAR(255) NULL,
  gram_sabha VARCHAR(255) NULL,
  category_scheduled_tribe VARCHAR(255) NULL,
  category_other_traditional_forest_dweller VARCHAR(255) NULL,
  title_land_area_measure VARCHAR(100) NULL,
  khasra_compartment_number VARCHAR(100) NULL,
  boundary_description TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dtuo_document FOREIGN KEY (document_id) REFERENCES master_documents (id) ON DELETE CASCADE,
  INDEX idx_dtuo_state (state),
  INDEX idx_dtuo_district (district),
  INDEX idx_dtuo_village (village)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE doc_title_community_forest_rights (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  document_id BIGINT UNSIGNED UNIQUE,
  community_right_holder_name VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  district VARCHAR(255) NULL,
  tehsil_taluka VARCHAR(255) NULL,
  village VARCHAR(255) NULL,
  gram_panchayat VARCHAR(255) NULL,
  gram_sabha VARCHAR(255) NULL,
  category_scheduled_tribe VARCHAR(255) NULL,
  category_other_traditional_forest_dweller VARCHAR(255) NULL,
  community_right_nature TEXT NULL,
  title_conditions TEXT NULL,
  khasra_compartment_number VARCHAR(100) NULL,
  boundary_description TEXT NULL,
  customary_boundary TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dtcfr_document FOREIGN KEY (document_id) REFERENCES master_documents (id) ON DELETE CASCADE,
  INDEX idx_dtcfr_state (state),
  INDEX idx_dtcfr_district (district),
  INDEX idx_dtcfr_village (village)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE doc_title_community_forest_resources (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  document_id BIGINT UNSIGNED UNIQUE,
  state VARCHAR(255) NULL,
  district VARCHAR(255) NULL,
  tehsil_taluka VARCHAR(255) NULL,
  village VARCHAR(255) NULL,
  gram_panchayat VARCHAR(255) NULL,
  gram_sabha VARCHAR(255) NULL,
  community_type_scheduled_tribe VARCHAR(255) NULL,
  community_type_other_tfd VARCHAR(255) NULL,
  community_type_both VARCHAR(255) NULL,
  khasra_compartment_number VARCHAR(100) NULL,
  boundary_description TEXT NULL,
  customary_boundary TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dtcfrs_document FOREIGN KEY (document_id) REFERENCES master_documents (id) ON DELETE CASCADE,
  INDEX idx_dtcfrs_state (state),
  INDEX idx_dtcfrs_district (district),
  INDEX idx_dtcfrs_village (village)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
